customhost = "Please enter AWS host name"
customuser = "Please provide user_name"
custompass = "provide password"
customdb = "enter DB naem"
custombucket = "enter S3 bucket name"
customregion = "Enter AWS region"
